-- @requires: legal, legal
-- Real shipped functions, grants and policies. Loading twice also tests reruns.
\set ON_ERROR_STOP on
\pset tuples_only on
\pset format unaligned

grant usage on schema public, auth to anon, authenticated;
grant select on public.auth_state to anon, authenticated;
create table public.legal_test_results (label text not null, ok boolean not null);
grant insert on public.legal_test_results to anon, authenticated;
create function public.legal_test_assert(condition boolean, label text)
returns void language plpgsql as $$ begin
  if condition is distinct from true then raise exception 'FAIL: %', label; end if;
  insert into public.legal_test_results values (label, true);
end $$;

select legal_test_assert(not has_table_privilege('authenticated', 'legal_acceptances', 'INSERT'), 'clients cannot forge receipts');
select legal_test_assert(not has_table_privilege('authenticated', 'legal_acceptances', 'UPDATE'), 'clients cannot rewrite receipt timestamps');
select legal_test_assert(not has_table_privilege('authenticated', 'legal_acceptances', 'DELETE'), 'clients cannot erase receipts');
select legal_test_assert(not has_table_privilege('authenticated', 'legal_versions', 'UPDATE'), 'clients cannot change required version');
select legal_test_assert(not has_function_privilege('anon', 'accept_legal(text)', 'EXECUTE'), 'unauthenticated role cannot accept');

update auth_state set uid = null, anon = true;
set role anon;
select legal_test_assert(legal_status()->>'version' = '2026-09-04' and legal_status()->>'accepted_at' is null, 'guest can review required version without an account');
do $$ begin
  begin perform accept_legal('2026-09-04'); raise exception 'FAIL: anon accepted';
  exception when insufficient_privilege then null; end;
end $$;
reset role;

set role authenticated;
do $$ begin
  begin perform accept_legal('2026-09-04'); raise exception 'FAIL: missing session accepted';
  exception when raise_exception then
    if sqlerrm <> 'A signed-in account is required' then raise; end if;
  end;
end $$;
reset role;

-- Supabase anonymous sessions have authenticated role, so the RPC must inspect
-- the server-owned auth.users field rather than relying on grants/JWT metadata.
update auth_state set uid = '22222222-2222-2222-2222-222222222222', anon = false;
update auth.users set is_anonymous = true where id = auth.uid();
set role authenticated;
do $$ begin
  begin perform accept_legal('2026-09-04'); raise exception 'FAIL: anonymous session accepted';
  exception when raise_exception then
    if sqlerrm <> 'A signed-in account is required' then raise; end if;
  end;
end $$;
reset role;

update auth_state set uid = '11111111-1111-1111-1111-111111111111', anon = false;
set role authenticated;
do $$ declare first_receipt jsonb; second_receipt jsonb; begin
  first_receipt := accept_legal('2026-09-04');
  second_receipt := accept_legal('2026-09-04');
  perform legal_test_assert(first_receipt = second_receipt, 'duplicate acceptance returns original receipt');
  perform legal_test_assert((first_receipt->>'accepted_at')::timestamptz = transaction_timestamp(), 'receipt date is generated by server');
  perform legal_test_assert(legal_status() = first_receipt, 'status returns caller receipt');
  perform legal_test_assert((select count(*) = 1 from legal_acceptances), 'one receipt per account and version');
  begin
    update legal_acceptances set accepted_at = '2000-01-01';
    raise exception 'FAIL: timestamp overwritten';
  exception when insufficient_privilege then null; end;
  begin perform accept_legal(null); raise exception 'FAIL: null version accepted';
  exception when raise_exception then
    if sqlerrm <> 'Review the current legal version first' then raise; end if;
  end;
end $$;
reset role;

update auth.users set is_anonymous = false where id = '22222222-2222-2222-2222-222222222222';
update auth_state set uid = '22222222-2222-2222-2222-222222222222';
set role authenticated;
select legal_test_assert((select count(*) = 0 from legal_acceptances), 'another account cannot read first account receipt');
select legal_test_assert(legal_status()->>'accepted_at' is null, 'status does not leak another account receipt');
select accept_legal('2026-09-04');
select legal_test_assert((select count(*) = 1 and bool_and(user_id = auth.uid()) from legal_acceptances), 'receipt ownership comes only from session');
reset role;

-- Publish a new release; old receipts remain audit history and do not satisfy it.
update legal_versions set is_current = false;
insert into legal_versions select 'next-release', terms_url, privacy_url, content_policy_url, true
  from legal_versions where version = '2026-09-04';
set role authenticated;
select legal_test_assert(legal_status()->>'version' = 'next-release' and legal_status()->>'accepted_at' is null, 'new version requires new acknowledgement');
do $$ begin
  begin perform accept_legal('2026-09-04'); raise exception 'FAIL: obsolete version accepted';
  exception when raise_exception then
    if sqlerrm <> 'Review the current legal version first' then raise; end if;
  end;
end $$;
select accept_legal('next-release');
select legal_test_assert((select count(*) = 2 from legal_acceptances), 'new acceptance preserves old version history');
reset role;
select legal_test_assert((select count(*) = 3 from legal_acceptances), 'receipts are distinct across accounts and releases');
delete from auth.users where id = '22222222-2222-2222-2222-222222222222';
select legal_test_assert((select count(*) = 1 from legal_acceptances), 'account deletion cascades only its own receipts');
select case when ok then '  PASS  ' else '  FAIL  ' end || label
  from public.legal_test_results order by label;
select '  ' || count(*) filter (where ok) || ' passed, '
       || count(*) filter (where not coalesce(ok, false)) || ' failed   [legal]'
  from public.legal_test_results;
