-- iTala v2 :: 0003 :: the domain
--
-- IDs are text and are generated by the CLIENT before any network call, so a
-- record created offline has its permanent identity immediately and syncs
-- cleanly. Timestamps that the app reasons about are bigint epoch
-- milliseconds, round-tripped exactly as the client wrote them; the
-- timestamptz columns are server-side bookkeeping the client never reads.

-- ---------------------------------------------------------------------------
-- leagues: the top-level container and the only unit of isolation.
-- v1 kept trackMisses in a global app_settings table shared by every league on
-- every device. It is a per-league property: a competitive league and a
-- Tuesday pickup run should not share a data-richness policy.
-- ---------------------------------------------------------------------------
create table if not exists public.leagues (
  id                 text primary key,
  name               text not null,
  season             text not null,
  kind               text not null default 'league' check (kind in ('league', 'recreational')),
  foul_out_limit     int  not null default 5 check (foul_out_limit between 1 and 10),
  regulation_periods int  not null default 4 check (regulation_periods in (2, 4)),
  track_misses       boolean not null default true,
  track_turnovers    boolean not null default false,
  created_at         bigint not null,
  updated_at         timestamptz not null default now()
);

comment on column public.leagues.season is
  'A free-text label such as "Spring 2026". NOT a date range: there is no rollover and no archiving.';
comment on column public.leagues.foul_out_limit is
  'FIBA is 5, NBA is 6. v1 capped this to 5 at read time to defend against legacy rows; v2 honours it.';

-- ---------------------------------------------------------------------------
-- teams. Soft-deleted, so history stays resolvable and the foreign keys
-- pointing at them stay valid.
-- ---------------------------------------------------------------------------
create table if not exists public.teams (
  id          text primary key,
  league_id   text not null references public.leagues (id) on delete cascade,
  name        text not null,
  color       text not null,
  logo_url    text,
  player_ids  text[] not null default '{}',
  archived_at bigint,
  deleted_at  bigint,
  updated_at  timestamptz not null default now()
);

comment on column public.teams.player_ids is
  'ORDERED. This is the roster display order and the default starting five. Order is meaningful; do not sort it.';
comment on column public.teams.logo_url is
  'A URL into Supabase Storage. v1 stored base64 data URIs inline in this row, which inflated every fetch.';
comment on column public.teams.archived_at is
  'Drop-in teams are archived a few days after their last game and hidden from roster pickers. Their games and box scores are kept forever.';

-- ---------------------------------------------------------------------------
-- players. Also soft-deleted: a removed player must still resolve by name in
-- historical box scores, rather than surfacing as the literal string "Player"
-- the way v1 did.
-- ---------------------------------------------------------------------------
create table if not exists public.players (
  id         text primary key,
  league_id  text not null references public.leagues (id) on delete cascade,
  name       text not null,
  number     text,
  person_id  text,
  deleted_at bigint,
  updated_at timestamptz not null default now()
);

comment on column public.players.number is
  'Jersey number as TEXT, deliberately. "00" and "0" are different numbers on a real roster.';
comment on column public.players.person_id is
  'Reserved for a future cross-league person identity. Nothing reads it yet; the column exists now because adding it later is expensive.';

-- ---------------------------------------------------------------------------
-- games. Note the real foreign keys to teams. v1 had none here, so deleting a
-- team left dangling games that crashed the live screen when opened.
--
-- The cascade from teams exists so that deleting a LEAGUE cleans up in one
-- pass. The app never hard-deletes a team; it sets deleted_at.
-- ---------------------------------------------------------------------------
create table if not exists public.games (
  id            text primary key,
  league_id     text not null references public.leagues (id) on delete cascade,
  home_team_id  text not null references public.teams (id) on delete cascade,
  away_team_id  text not null references public.teams (id) on delete cascade,
  status        text not null check (status in ('live', 'final')),
  scheduled_at  bigint,
  location      text,
  finished_at   bigint,
  home_on_court text[] not null default '{}',
  away_on_court text[] not null default '{}',
  period        int not null default 1 check (period between 1 and 9),
  updated_at    timestamptz not null default now(),
  constraint games_distinct_teams check (home_team_id <> away_team_id)
);

comment on column public.games.finished_at is
  'Set only on the transition to final. Standings ordering and streak derivation depend on it.';

-- ---------------------------------------------------------------------------
-- events: THE LEDGER. Append-only, immutable once written, and the only
-- source of numeric truth in the entire system.
--
-- v1 left the type column with no check constraint and validated client-side.
-- With no legacy strings to tolerate, the database enforces its own enum.
-- ---------------------------------------------------------------------------
create table if not exists public.events (
  id         text primary key,
  league_id  text not null references public.leagues (id) on delete cascade,
  game_id    text not null references public.games (id) on delete cascade,
  team_id    text not null references public.teams (id) on delete cascade,
  player_id  text references public.players (id) on delete set null,
  type       text not null check (type in (
    'fg2_make', 'fg2_miss',
    'fg3_make', 'fg3_miss',
    'ft_make',  'ft_miss',
    'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
    'timeout'
  )),
  period     int not null check (period between 1 and 9),
  ts         bigint not null,
  note       text,
  created_at timestamptz not null default now()
);

comment on table public.events is
  'The atomic unit of truth. Box scores, scores, standings and career stats are folds over this table and are never stored.';
comment on column public.events.player_id is
  'NULL is MEANINGFUL, not missing: it marks a team-level event such as a timeout. Team-level rows must still appear in team totals.';
comment on column public.events.id is
  'Client-generated. This primary key is the idempotency guard that makes a replayed insert safe and double-logging impossible.';

-- ---------------------------------------------------------------------------
-- Indexes, each serving a named access path.
-- ---------------------------------------------------------------------------
create index if not exists teams_league_id_idx   on public.teams (league_id);
create index if not exists players_league_id_idx on public.players (league_id);
create index if not exists games_league_id_idx   on public.games (league_id);
create index if not exists events_league_id_idx  on public.events (league_id);
-- By far the hottest path: every box score, line score, team-foul and
-- foul-out computation filters events by game.
create index if not exists events_game_id_idx    on public.events (game_id);
-- Not used by the client today, which fetches and filters in memory, but the
-- spectator web view queries a single player's history directly.
create index if not exists events_player_id_idx  on public.events (player_id);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['leagues', 'teams', 'players', 'games'] loop
    execute format('drop trigger if exists set_updated_at_%1$s on public.%1$I', t);
    execute format(
      'create trigger set_updated_at_%1$s before update on public.%1$I
         for each row execute function public.set_updated_at()', t);
  end loop;
end;
$$;
